<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Budget;


/**
 * BudgetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BudgetRepository extends \Doctrine\ORM\EntityRepository
{
        public function phpUnitAddBudget($title,$value,$start_date,$end_date){
                $budget = new Budget();
                $budget->setTitle($title);
                $budget->setValue($value);
                $budget->setStartDate($start_date);
                $budget->setEndDate($end_date);

                $em = $this->getDoctrine()->getManager();
                $em->persist($budget);
                $em->flush();

                return $budget;

        }
}
