<?php

namespace AppBundle\Repository;

/**
 * InitiativeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InitiativeRepository extends \Doctrine\ORM\EntityRepository
{
}
