<?php

namespace AppBundle\Repository;

/**
 * InitiativeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InitiativeRepository extends \Doctrine\ORM\EntityRepository
{

	public function phpUnitAddInitiative($title,$value,$id){

		$initiative = new Initiative();
        $initiative->setTitle($title);
        $initiative->setIdBudget($id);
        $initiative->setValue($value);

        $em = $this->getDoctrine()->getManager();
        $em->persist($initiative);
        $em->flush();

        return $initiative;

	}
}
