app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    

add_budget:
    path:     /addBudget
    defaults: { _controller: AppBundle:Budget:addBudget }

add_initiative:
    path:     /addInitiative
    defaults: { _controller: AppBundle:Initiative:addInitiative }

    # redirecting the admin home
root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: add_budget
        permanent: true

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"