app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
index:
    path:     /
    defaults: { _controller: AppBundle:Default:index }


add_budget:
    path:     /addBudget
    defaults: { _controller: AppBundle:Budget:addBudget }

add_initiative:
    path:     /addInitiative
    defaults: { _controller: AppBundle:Initiative:addInitiative }

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"