
add_budget:
    path:     /addBudget
    defaults: { _controller: AppBundle:Budget:addBudget }

add_initiative:
    path:     /addInitiative
    defaults: { _controller: AppBundle:Initiative:addInitiative }


index:
    path:     /
    defaults: { _controller: AppBundle:Default:index }
