AppBundle\Entity\Initiative:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\InitiativeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
            column: title
        value:
            type: float
            nullable: false
            column: value
    lifecycleCallbacks: {  }
